---
title: "Project myoV-Pi"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
#library(biophysr)
library(lasertrapr)
library(aomisc)
#devtools::install_github("onofriAndreaPG/aomisc")
library(drc)
library(tidyverse)
library(magrittr)
library(gt)
library(RColorBrewer)
library(plotrix)
library(plotly)
library(broom)
library(cowplot)

trap_selected_project <- '/Users/brentscott/lasertrapr/project_myoV-phosphate'

  # directions <- list_files(trap_selected_project,
  #                          pattern = "directions.csv",
  #                          recursive = TRUE)
  # 
  # event_p <- list_files(trap_selected_project,
  #                       pattern = "measured-events.csv",
  #                       recursive = TRUE)
  # 
  # raw_data_paths <- list_files(trap_selected_project,
  #                              pattern = "grouped",
  #                              recursive = TRUE)


trap_data_paths <- lasertrapr:::list_files(trap_selected_project,
                         pattern = "trap-data.rds",
                         recursive = TRUE)
  
  
  # read_exported_directions <- bind_rows(map(directions$path, read_csv)) %>% 
  #   mutate(grouped_file = raw_data_paths$path) %>%
  #   filter(report == "success") %>%
  #   mutate(event_paths = event_p$path) %>%
  #   rename(quality_control = `Quality Control`) %>%
  #   filter(quality_control == TRUE) %>%
  #   mutate(split = event_paths) %>%
  #   separate(split, c('nada', 'u', 'b', 'box', 'mbl', 'b2', 'data', 'me', 'trap', 'project', 'conditions', 'date', 'res', 'e', 'filename'), sep = '/')


trap_data <- bind_rows(purrr::map(trap_data_paths$path, readRDS)) %>% 
  filter(report == "success", quality_control == T)


 # all_hmm_events <- suppressMessages(map(read_exported_directions$event_paths, read_csv, col_names = TRUE))


  # for(s in 1:nrow(read_exported_directions)){
  #   all_hmm_events[[s]] <- cbind(all_hmm_events[[s]], read_exported_directions$conditions[[s]])
  # }
 event_files_filtered <- trap_data %>% 
   dplyr::select(project, conditions, date, obs, results) %>% 
   mutate(events = map(results, 'events'),
          conditions2 = conditions) %>% 
   unnest(cols = c(events)) %>% 
   dplyr::select(!results) %>% 
   tidyr::separate(conditions, c("myo", "ph", "pi"), sep = "_")

  #####summarise


  #####summarise


  #all_grouped <- suppressMessages(map(read_exported_directions$grouped_file, read_tsv, col_names = FALSE))

  # all_grouped <- list()
  # for(g in 1:nrow(read_exported_directions)){
  #   if(str_sub(read_exported_directions$grouped_file[[g]], -3) == 'txt'){
  #     all_grouped[[g]] <- read_tsv(read_exported_directions$grouped_file[[g]], col_names = c('bead', 'trap'))
  #   } else {
  #     all_grouped[[g]] <- read_csv(read_exported_directions$grouped_file[[g]], col_names = TRUE)
  #   }
  # 
  #   all_grouped[[g]] <- cbind(all_grouped[[g]], read_exported_directions$conditions[[g]])
  # }


  all_grouped <- trap_data %>% 
   dplyr::select(project, conditions, date, obs, grouped) %>% 
    unnest(cols = grouped)
    
    
  # all_grouped <- bind_rows(all_grouped) %>%
  #   rename(conditions = 'read_exported_directions$conditions[[g]]') %>% 
  #   mutate(conditions = as.character(conditions))

  get_time <- all_grouped %>%
    dplyr::group_by(conditions) %>% 
    dplyr::summarize(minutes = round((length(bead)/5000)/60, 2)) %>% 
    mutate(conditions2 = conditions) %>% 
    tidyr::separate(conditions, c("myo", "ph", "pi"), sep = "_")
  # separate(conditions, c("myo", "ph", "phosphate"), sep = "_")


  # num_events <- event_files_filtered %>%
  #   group_by(conditions) %>%
  #   count()


  summarize_trap <- event_files_filtered %>%
    dplyr::group_by(myo, ph, pi) %>%
    dplyr::summarize(time_on_avg = mean(time_on_ms),
              time_on_se = plotrix::std.error(time_on_ms, na.rm = TRUE),
              time_on_median = median(time_on_ms, na.rm = TRUE),
              time_off_avg = mean(time_off_ms, na.rm = TRUE),
              time_off_se = plotrix::std.error(time_off_ms, na.rm = TRUE),
              time_off_median = median(time_off_ms, na.rm = TRUE), 
              displacement_avg = mean(displacement_nm, na.rm = TRUE),
              displacement_se = plotrix::std.error(displacement_nm, na.rm = TRUE),
              force_avg = mean(force, na.rm = TRUE),
              force_se = plotrix::std.error(force, na.rm = TRUE),
              num_events = n()) %>%
    right_join(get_time) %>% 
    rename('conditions' = conditions2)

summarize_trap$conditions <- factor(summarize_trap$conditions,
                                           levels = c("myoV-WT_pH-7.0_control",
                                                      
                                                      "myoV-WT_pH-7.0_30mM-Pi",
                                                      "myoV-S217A_pH-7.0_control",
                                                      
                                                    
                                                      "myoV-S217A_pH-7.0_30mM-Pi"))

 
```
    
Summary Table
=====================================  
Row 
-------------------------------------
    
### Summary Table
    
```{r}
summarize_trap %>% 
  arrange(conditions) %>% 
   ungroup() %>% 
  separate(conditions, c("Myosin", "pH", "Pi"), sep = "_") %>% 
  dplyr::select(Myosin,
                Pi,
        "Step Size (nm)" = displacement_avg,
         "Force (pN)" = force_avg,
         "Avg Time On (ms)" = time_on_avg,
         'Median Time on (ms)' = time_on_median,
         "Time Off (ms)" = time_off_avg,
         "No. Events" = num_events,
         "Minutes Collected" = minutes
         ) %>% 
  mutate_if(is.numeric, ~round(.,digits = 2)) %>% 
  gt() %>% 
  tab_header(
    title = "Myosin-V Phosphate",
    subtitle = "Project Summary"
  ) %>% 
  tab_spanner(label = "Conditions", columns = vars(Myosin, Pi), gather = TRUE) %>%
  tab_style(
    style = cell_fill(color = "blue", alpha = 0.25),
    locations = cells_body(
      rows = Myosin == 'myoV-WT')
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "red", alpha = 0.25)
    ),
    locations = cells_body(
      rows = Myosin == 'myoV-S217A')
  )
```
 
Distributions
=====================================  

Row {.tabset .tabset-fade}
-------------------------------------
    
### Step Size
    
```{r}
event_files_filtered$conditions2 <- factor(event_files_filtered$conditions2,
                                           levels = c("myoV-WT_pH-7.0_control",
                                                      
                                                    
                                                      "myoV-WT_pH-7.0_30mM-Pi",
                                                      "myoV-S217A_pH-7.0_control",
                                                      
                                                    
                                                      "myoV-S217A_pH-7.0_30mM-Pi"))

event_files_filtered$pi <-  factor(event_files_filtered$pi,
                                    levels = c("control", "30mM-Pi"))

event_files_filtered$myo <-  factor(event_files_filtered$myo,
                                    levels = c("myoV-WT", "myoV-S217A"))

  blu <- RColorBrewer::brewer.pal(n = 9, "Blues")[c( 6, 8)]
  red <- RColorBrewer::brewer.pal(n = 9, "Reds")[c( 6,  8)]
  colors <- c(blu, red)
ggplot(data = event_files_filtered,
                        aes(x = displacement_nm,
                            fill = conditions2))+
    geom_histogram(aes(y = stat(density)),
                     binwidth = 3,
                     color = "black")+
    facet_grid(myo~pi)+
    xlab("Step Size (nm)")+
    scale_y_continuous(expand = c(0,0))+
    #scale_x_continuous(breaks = seq(-40, 40, by = 5))+
    scale_fill_manual(values = colors)+
    #scale_fill_brewer(palette = "Dark2")+
      theme_linedraw()+
      theme(panel.grid = element_blank(),
            legend.position = 'none')+
    ggtitle("Step Size Distributions")

```
    
### Time On

```{r}
ggplot(data = event_files_filtered,
                        aes(x = time_on_ms,
                            fill = conditions2))+
      geom_histogram(aes(y = stat(density)),
                     binwidth = 25,
                     color = "black")+
      facet_grid(myo~pi)+
      xlab("Time on (ms)")+
      scale_y_continuous(expand = c(0,0))+
      #scale_x_continuous(breaks = seq(0, 6000, by = 100))+
      coord_cartesian(c(0, 1000))+
      scale_fill_manual(values = colors)+
      #scale_fill_brewer(palette = "Dark2")+
      theme_linedraw()+
      theme(panel.grid = element_blank(),
            legend.position = "none")+
  ggtitle("Time On Distributions")
```


### Time Off

```{r}
ggplot(data = event_files_filtered,
                           aes(x = time_off_ms,
                               fill = conditions2))+
      geom_histogram(aes(y = stat(density)),
                     binwidth = 100,
                     color = "black")+
      facet_grid(myo~pi)+
      xlab("Time off (ms)")+
      scale_y_continuous(expand = c(0,0))+
      #scale_x_continuous(breaks = seq(0, 20000, by = 500))+
      coord_cartesian(c(0, 2000))+
      scale_fill_manual(values = colors)+
      #scale_fill_brewer(palette = "Dark2")+
      theme_linedraw()+
      theme(panel.grid = element_blank(),
            legend.position = "none")+
  ggtitle("Time Off Distributions")

```


### Force

```{r}
ggplot(data = event_files_filtered,
                            aes(x = force,
                                fill = conditions2))+
      geom_histogram(aes(y = stat(density)),
                     binwidth = 0.1,
                     color = "black")+
      facet_grid(myo~pi)+
      xlab("Time off (ms)")+
      scale_y_continuous(expand = c(0,0))+
      #scale_x_continuous(breaks = seq(0, 20000, by = 500))+
      scale_fill_manual(values = colors)+
      #scale_fill_brewer(palette = "Dark2")+
      theme_linedraw()+
      theme(panel.grid = element_blank(),
            legend.position = "none")+
  ggtitle("Force Distributions")
```


Time On Survival 
=====================================

```{r, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(tidyverse)
library(survival)
library(survminer)
library(magrittr)
library(RColorBrewer)

```

 
```{r echo=FALSE, fig.height=8, fig.width=12, message=FALSE, warning=FALSE}
df <- event_files_filtered %>% 
  #mutate(conditions = condition) 
  #separate('condition', c('myo', 'pH', 'pi'), sep = '_') %>% 
  mutate(#pi = ifelse(str_detect(pi, '2nd'), 'Control', 
                     #ifelse(str_detect(pi, '15'), '15mM', '30mM')),
         myo01 = ifelse(str_detect(myo, 'WT'), 0, 1))

df$myo <- factor(df$myo, levels = c('myoV-WT', 'myoV-S217A'))
df$pi <- factor(df$pi, levels = c('control', '30mM-Pi'))

df$myo01 <- factor(df$myo01, levels = c(0, 1))
#df$pi <- factor(df$pi, levels = c('Control', '15mM', '30mM'))


#df <- data %>% filter(condition=='myoV-S217A_pH7.0_15mM-Pi')

fit <- survfit(Surv(time_on_ms) ~ myo01 + pi, data = df)
#fit
#fit
# Summary of survival curves
# summary(fit)
# # Access to the sort summary table
# summary(fit)$table

blu <-  brewer.pal(9, 'Blues')[c(4, 8)]
red <-   brewer.pal(9, 'Reds')[c( 4,  8)]
ggsurvival <- ggsurvplot(fit, 
          ggtheme = theme_linedraw(base_size = 20), # Change ggplot2 theme
          palette = c(blu, red),
          xlim = c(0, 1000),
          break.time.by = 150,
           legend.labs = c('WT Control', 
                          
                           'WT 30mM-Pi', 
                            'S217A Control', 
           
                           'S217A 30mM-Pi'),
           fun = 'event'
          )

m.labs <- c('WT', 'S217A')
names(m.labs) <- c('0', '1')
ggsurvival2 <- ggsurvival$plot +
  facet_wrap(~myo01,
               labeller = labeller(myo01 = m.labs))+
  xlab('Time (ms)')+
  theme(panel.grid = element_blank(),
        legend.title = element_blank())

ggsurvival2
```



Event Frequency
==============================

Row {.tabset .tabset-fade}
-------------------------------------

### Events Starting

```{r, fig.width=10, fig.heigh=12, echo=FALSE, message=FALSE, warning=FALSE}
ef <- trap_data %>% 
   dplyr::select(project, conditions, date, obs, results) %>% 
   mutate(event_freq = map(results, 'event_freq'),
          conditions2 = conditions) %>% 
   unnest(cols = c(event_freq)) %>% 
   dplyr::select(!results) %>% 
   tidyr::separate(conditions, c("myo", "ph", "pi"), sep = "_") %>% 
  rename('conditions' = conditions2)


  
  
  
  ef$conditions <- factor(ef$conditions,  levels = c("myoV-WT_pH-7.0_control",


                                                      "myoV-WT_pH-7.0_30mM-Pi",
                                                      "myoV-S217A_pH-7.0_control",

                                                      "myoV-S217A_pH-7.0_30mM-Pi"))
    
  ef$myo <- factor(ef$myo, levels = c('myoV-WT', 'myoV-S217A'))
  ef$pi <- factor(ef$pi, levels = c('control', '30mM-Pi'))
  
   blu <- brewer.pal(n = 9, "Blues")[c(4, 8)]
  red <- brewer.pal(n = 9, "Reds")[c(4, 8)]
  colors <- c(blu, red)
  
  ggplot(data = ef)+
    geom_histogram(aes(x = freq_start, y= stat(density), fill = conditions), 
                   color = 'black', 
                   binwidth = 1)+
    facet_wrap(~conditions, scales = 'free')+
    scale_fill_manual(values = colors)+
    theme_linedraw()+
    xlab('Number of Events Starting Every Second')+
    theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank())
```

### Events Ending


```{r, fig.width=10, fig.heigh=12, echo=FALSE, message=FALSE, warning=FALSE}
ef <- trap_data %>%
   dplyr::select(project, conditions, date, obs, results) %>%
   mutate(event_freq = map(results, 'event_freq'),
          conditions2 = conditions) %>%
   unnest(cols = c(event_freq)) %>%
   dplyr::select(!results) %>%
   tidyr::separate(conditions, c("myo", "ph", "pi"), sep = "_") %>%
  rename('conditions' = conditions2)





  ef$conditions <- factor(ef$conditions,  levels = c("myoV-WT_pH-7.0_control",


                                                      "myoV-WT_pH-7.0_30mM-Pi",
                                                      "myoV-S217A_pH-7.0_control",

                                                      "myoV-S217A_pH-7.0_30mM-Pi"))

  ef$myo <- factor(ef$myo, levels = c('myoV-WT', 'myoV-S217A'))
  ef$pi <- factor(ef$pi, levels = c('control', '30mM-Pi'))

   blu <- brewer.pal(n = 9, "Blues")[c(4, 8)]
  red <- brewer.pal(n = 9, "Reds")[c(4, 8)]
  colors <- c(blu, red)

  ggplot(data = ef)+
    geom_histogram(aes(x = freq_stop, y= stat(density), fill = conditions), 
                   color = 'black', 
                   binwidth = 1)+
    facet_wrap(~conditions, scales = 'free')+
    scale_fill_manual(values = colors)+
    theme_linedraw()+
    xlab('Number of Events Ending Every Second')+
    theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank())
```
